var namespace_catch =
[
    [ "Benchmark", "namespace_catch_1_1_benchmark.html", "namespace_catch_1_1_benchmark" ],
    [ "clara", "namespace_catch_1_1clara.html", "namespace_catch_1_1clara" ],
    [ "detail", "namespace_catch_1_1detail.html", "namespace_catch_1_1detail" ],
    [ "Detail", "namespace_catch_1_1_detail.html", "namespace_catch_1_1_detail" ],
    [ "Generators", "namespace_catch_1_1_generators.html", "namespace_catch_1_1_generators" ],
    [ "Matchers", "namespace_catch_1_1_matchers.html", "namespace_catch_1_1_matchers" ],
    [ "TestCaseTracking", "namespace_catch_1_1_test_case_tracking.html", "namespace_catch_1_1_test_case_tracking" ],
    [ "always_false", "struct_catch_1_1always__false.html", null ],
    [ "AssertionHandler", "class_catch_1_1_assertion_handler.html", "class_catch_1_1_assertion_handler" ],
    [ "AssertionInfo", "struct_catch_1_1_assertion_info.html", "struct_catch_1_1_assertion_info" ],
    [ "AssertionReaction", "struct_catch_1_1_assertion_reaction.html", "struct_catch_1_1_assertion_reaction" ],
    [ "AssertionResult", "class_catch_1_1_assertion_result.html", "class_catch_1_1_assertion_result" ],
    [ "AssertionResultData", "struct_catch_1_1_assertion_result_data.html", "struct_catch_1_1_assertion_result_data" ],
    [ "AssertionStats", "struct_catch_1_1_assertion_stats.html", "struct_catch_1_1_assertion_stats" ],
    [ "AutomakeReporter", "struct_catch_1_1_automake_reporter.html", "struct_catch_1_1_automake_reporter" ],
    [ "AutoReg", "struct_catch_1_1_auto_reg.html", "struct_catch_1_1_auto_reg" ],
    [ "BinaryExpr", "class_catch_1_1_binary_expr.html", "class_catch_1_1_binary_expr" ],
    [ "Capturer", "class_catch_1_1_capturer.html", "class_catch_1_1_capturer" ],
    [ "CaseSensitive", "struct_catch_1_1_case_sensitive.html", "struct_catch_1_1_case_sensitive" ],
    [ "Colour", "struct_catch_1_1_colour.html", "struct_catch_1_1_colour" ],
    [ "CompactReporter", "struct_catch_1_1_compact_reporter.html", "struct_catch_1_1_compact_reporter" ],
    [ "Config", "class_catch_1_1_config.html", "class_catch_1_1_config" ],
    [ "ConfigData", "struct_catch_1_1_config_data.html", "struct_catch_1_1_config_data" ],
    [ "ConsoleReporter", "struct_catch_1_1_console_reporter.html", "struct_catch_1_1_console_reporter" ],
    [ "Context", "class_catch_1_1_context.html", "class_catch_1_1_context" ],
    [ "Counts", "struct_catch_1_1_counts.html", "struct_catch_1_1_counts" ],
    [ "CumulativeReporterBase", "struct_catch_1_1_cumulative_reporter_base.html", "struct_catch_1_1_cumulative_reporter_base" ],
    [ "Decomposer", "struct_catch_1_1_decomposer.html", "struct_catch_1_1_decomposer" ],
    [ "ErrnoGuard", "class_catch_1_1_errno_guard.html", "class_catch_1_1_errno_guard" ],
    [ "ExceptionTranslatorRegistrar", "class_catch_1_1_exception_translator_registrar.html", "class_catch_1_1_exception_translator_registrar" ],
    [ "ExceptionTranslatorRegistry", "class_catch_1_1_exception_translator_registry.html", "class_catch_1_1_exception_translator_registry" ],
    [ "ExprLhs", "class_catch_1_1_expr_lhs.html", "class_catch_1_1_expr_lhs" ],
    [ "FatalConditionHandler", "class_catch_1_1_fatal_condition_handler.html", "class_catch_1_1_fatal_condition_handler" ],
    [ "FatalConditionHandlerGuard", "class_catch_1_1_fatal_condition_handler_guard.html", "class_catch_1_1_fatal_condition_handler_guard" ],
    [ "GeneratorException", "class_catch_1_1_generator_exception.html", "class_catch_1_1_generator_exception" ],
    [ "GroupInfo", "struct_catch_1_1_group_info.html", "struct_catch_1_1_group_info" ],
    [ "IConfig", "struct_catch_1_1_i_config.html", "struct_catch_1_1_i_config" ],
    [ "IContext", "struct_catch_1_1_i_context.html", "struct_catch_1_1_i_context" ],
    [ "IExceptionTranslator", "struct_catch_1_1_i_exception_translator.html", "struct_catch_1_1_i_exception_translator" ],
    [ "IExceptionTranslatorRegistry", "struct_catch_1_1_i_exception_translator_registry.html", "struct_catch_1_1_i_exception_translator_registry" ],
    [ "IGeneratorTracker", "struct_catch_1_1_i_generator_tracker.html", "struct_catch_1_1_i_generator_tracker" ],
    [ "IMutableContext", "struct_catch_1_1_i_mutable_context.html", "struct_catch_1_1_i_mutable_context" ],
    [ "IMutableEnumValuesRegistry", "struct_catch_1_1_i_mutable_enum_values_registry.html", "struct_catch_1_1_i_mutable_enum_values_registry" ],
    [ "IMutableRegistryHub", "struct_catch_1_1_i_mutable_registry_hub.html", "struct_catch_1_1_i_mutable_registry_hub" ],
    [ "IRegistryHub", "struct_catch_1_1_i_registry_hub.html", "struct_catch_1_1_i_registry_hub" ],
    [ "IReporterFactory", "struct_catch_1_1_i_reporter_factory.html", "struct_catch_1_1_i_reporter_factory" ],
    [ "IReporterRegistry", "struct_catch_1_1_i_reporter_registry.html", "struct_catch_1_1_i_reporter_registry" ],
    [ "IResultCapture", "struct_catch_1_1_i_result_capture.html", "struct_catch_1_1_i_result_capture" ],
    [ "IRunner", "struct_catch_1_1_i_runner.html", "struct_catch_1_1_i_runner" ],
    [ "is_callable", "struct_catch_1_1is__callable.html", null ],
    [ "is_callable< Fun(Args...)>", "struct_catch_1_1is__callable_3_01_fun_07_args_8_8_8_08_4.html", null ],
    [ "is_callable_tester", "struct_catch_1_1is__callable__tester.html", null ],
    [ "is_range", "struct_catch_1_1is__range.html", null ],
    [ "is_range< disabled_range >", "struct_catch_1_1is__range_3_01disabled__range_01_4.html", null ],
    [ "ISingleton", "struct_catch_1_1_i_singleton.html", "struct_catch_1_1_i_singleton" ],
    [ "IStream", "struct_catch_1_1_i_stream.html", "struct_catch_1_1_i_stream" ],
    [ "IStreamingReporter", "struct_catch_1_1_i_streaming_reporter.html", "struct_catch_1_1_i_streaming_reporter" ],
    [ "ITagAliasRegistry", "struct_catch_1_1_i_tag_alias_registry.html", "struct_catch_1_1_i_tag_alias_registry" ],
    [ "ITestCaseRegistry", "struct_catch_1_1_i_test_case_registry.html", "struct_catch_1_1_i_test_case_registry" ],
    [ "ITestInvoker", "struct_catch_1_1_i_test_invoker.html", "struct_catch_1_1_i_test_invoker" ],
    [ "ITransientExpression", "struct_catch_1_1_i_transient_expression.html", "struct_catch_1_1_i_transient_expression" ],
    [ "JunitReporter", "class_catch_1_1_junit_reporter.html", "class_catch_1_1_junit_reporter" ],
    [ "LazyExpression", "class_catch_1_1_lazy_expression.html", "class_catch_1_1_lazy_expression" ],
    [ "LazyStat", "struct_catch_1_1_lazy_stat.html", "struct_catch_1_1_lazy_stat" ],
    [ "LeakDetector", "struct_catch_1_1_leak_detector.html", "struct_catch_1_1_leak_detector" ],
    [ "ListenerRegistrar", "class_catch_1_1_listener_registrar.html", "class_catch_1_1_listener_registrar" ],
    [ "ListeningReporter", "class_catch_1_1_listening_reporter.html", "class_catch_1_1_listening_reporter" ],
    [ "MatchExpr", "class_catch_1_1_match_expr.html", "class_catch_1_1_match_expr" ],
    [ "MessageBuilder", "struct_catch_1_1_message_builder.html", "struct_catch_1_1_message_builder" ],
    [ "MessageInfo", "struct_catch_1_1_message_info.html", "struct_catch_1_1_message_info" ],
    [ "MessageStream", "struct_catch_1_1_message_stream.html", "struct_catch_1_1_message_stream" ],
    [ "NameAndTags", "struct_catch_1_1_name_and_tags.html", "struct_catch_1_1_name_and_tags" ],
    [ "NonCopyable", "class_catch_1_1_non_copyable.html", "class_catch_1_1_non_copyable" ],
    [ "OcMethod", "class_catch_1_1_oc_method.html", "class_catch_1_1_oc_method" ],
    [ "Option", "class_catch_1_1_option.html", "class_catch_1_1_option" ],
    [ "pluralise", "struct_catch_1_1pluralise.html", "struct_catch_1_1pluralise" ],
    [ "RedirectedStdErr", "class_catch_1_1_redirected_std_err.html", "class_catch_1_1_redirected_std_err" ],
    [ "RedirectedStdOut", "class_catch_1_1_redirected_std_out.html", "class_catch_1_1_redirected_std_out" ],
    [ "RedirectedStream", "class_catch_1_1_redirected_stream.html", "class_catch_1_1_redirected_stream" ],
    [ "RedirectedStreams", "class_catch_1_1_redirected_streams.html", "class_catch_1_1_redirected_streams" ],
    [ "RegistrarForTagAliases", "struct_catch_1_1_registrar_for_tag_aliases.html", "struct_catch_1_1_registrar_for_tag_aliases" ],
    [ "ReporterConfig", "struct_catch_1_1_reporter_config.html", "struct_catch_1_1_reporter_config" ],
    [ "ReporterPreferences", "struct_catch_1_1_reporter_preferences.html", "struct_catch_1_1_reporter_preferences" ],
    [ "ReporterRegistrar", "class_catch_1_1_reporter_registrar.html", "class_catch_1_1_reporter_registrar" ],
    [ "ReporterRegistry", "class_catch_1_1_reporter_registry.html", "class_catch_1_1_reporter_registry" ],
    [ "ResultDisposition", "struct_catch_1_1_result_disposition.html", "struct_catch_1_1_result_disposition" ],
    [ "ResultWas", "struct_catch_1_1_result_was.html", "struct_catch_1_1_result_was" ],
    [ "ReusableStringStream", "class_catch_1_1_reusable_string_stream.html", "class_catch_1_1_reusable_string_stream" ],
    [ "RunContext", "class_catch_1_1_run_context.html", "class_catch_1_1_run_context" ],
    [ "RunTests", "struct_catch_1_1_run_tests.html", "struct_catch_1_1_run_tests" ],
    [ "ScopedMessage", "class_catch_1_1_scoped_message.html", "class_catch_1_1_scoped_message" ],
    [ "Section", "class_catch_1_1_section.html", "class_catch_1_1_section" ],
    [ "SectionEndInfo", "struct_catch_1_1_section_end_info.html", "struct_catch_1_1_section_end_info" ],
    [ "SectionInfo", "struct_catch_1_1_section_info.html", "struct_catch_1_1_section_info" ],
    [ "SectionStats", "struct_catch_1_1_section_stats.html", "struct_catch_1_1_section_stats" ],
    [ "Session", "class_catch_1_1_session.html", "class_catch_1_1_session" ],
    [ "ShowDurations", "struct_catch_1_1_show_durations.html", "struct_catch_1_1_show_durations" ],
    [ "SignalDefs", "struct_catch_1_1_signal_defs.html", "struct_catch_1_1_signal_defs" ],
    [ "SimplePcg32", "class_catch_1_1_simple_pcg32.html", "class_catch_1_1_simple_pcg32" ],
    [ "Singleton", "class_catch_1_1_singleton.html", null ],
    [ "SonarQubeReporter", "struct_catch_1_1_sonar_qube_reporter.html", "struct_catch_1_1_sonar_qube_reporter" ],
    [ "SourceLineInfo", "struct_catch_1_1_source_line_info.html", "struct_catch_1_1_source_line_info" ],
    [ "StartupExceptionRegistry", "class_catch_1_1_startup_exception_registry.html", "class_catch_1_1_startup_exception_registry" ],
    [ "StreamEndStop", "struct_catch_1_1_stream_end_stop.html", "struct_catch_1_1_stream_end_stop" ],
    [ "StreamingReporterBase", "struct_catch_1_1_streaming_reporter_base.html", "struct_catch_1_1_streaming_reporter_base" ],
    [ "StringMaker", "struct_catch_1_1_string_maker.html", null ],
    [ "StringMaker< bool >", "struct_catch_1_1_string_maker_3_01bool_01_4.html", null ],
    [ "StringMaker< Catch::Detail::Approx >", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", null ],
    [ "StringMaker< char * >", "struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", null ],
    [ "StringMaker< char >", "struct_catch_1_1_string_maker_3_01char_01_4.html", null ],
    [ "StringMaker< char const * >", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", null ],
    [ "StringMaker< char[SZ]>", "struct_catch_1_1_string_maker_3_01char_0f_s_z_0e_4.html", null ],
    [ "StringMaker< double >", "struct_catch_1_1_string_maker_3_01double_01_4.html", null ],
    [ "StringMaker< float >", "struct_catch_1_1_string_maker_3_01float_01_4.html", null ],
    [ "StringMaker< has_maker >", "struct_catch_1_1_string_maker_3_01has__maker_01_4.html", null ],
    [ "StringMaker< has_maker_and_operator >", "struct_catch_1_1_string_maker_3_01has__maker__and__operator_01_4.html", null ],
    [ "StringMaker< int >", "struct_catch_1_1_string_maker_3_01int_01_4.html", null ],
    [ "StringMaker< long >", "struct_catch_1_1_string_maker_3_01long_01_4.html", null ],
    [ "StringMaker< long long >", "struct_catch_1_1_string_maker_3_01long_01long_01_4.html", null ],
    [ "StringMaker< R C::* >", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
    [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", null ],
    [ "StringMaker< signed char >", "struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", null ],
    [ "StringMaker< signed char[SZ]>", "struct_catch_1_1_string_maker_3_01signed_01char_0f_s_z_0e_4.html", null ],
    [ "StringMaker< std::nullptr_t >", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", null ],
    [ "StringMaker< std::string >", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", null ],
    [ "StringMaker< std::wstring >", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", null ],
    [ "StringMaker< stringmaker_range >", "struct_catch_1_1_string_maker_3_01stringmaker__range_01_4.html", null ],
    [ "StringMaker< StringMakerException >", "struct_catch_1_1_string_maker_3_01_string_maker_exception_01_4.html", null ],
    [ "StringMaker< T * >", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
    [ "StringMaker< T[SZ]>", "struct_catch_1_1_string_maker_3_01_t_0f_s_z_0e_4.html", null ],
    [ "StringMaker< unsigned char >", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", null ],
    [ "StringMaker< unsigned char[SZ]>", "struct_catch_1_1_string_maker_3_01unsigned_01char_0f_s_z_0e_4.html", null ],
    [ "StringMaker< unsigned int >", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", null ],
    [ "StringMaker< unsigned long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", null ],
    [ "StringMaker< unsigned long long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", null ],
    [ "StringMaker< wchar_t * >", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", null ],
    [ "StringMaker< wchar_t const * >", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", null ],
    [ "StringRef", "class_catch_1_1_string_ref.html", "class_catch_1_1_string_ref" ],
    [ "StringStreams", "struct_catch_1_1_string_streams.html", "struct_catch_1_1_string_streams" ],
    [ "SummaryColumn", "struct_catch_1_1_summary_column.html", "struct_catch_1_1_summary_column" ],
    [ "TablePrinter", "class_catch_1_1_table_printer.html", "class_catch_1_1_table_printer" ],
    [ "TagAlias", "struct_catch_1_1_tag_alias.html", "struct_catch_1_1_tag_alias" ],
    [ "TagAliasRegistry", "class_catch_1_1_tag_alias_registry.html", "class_catch_1_1_tag_alias_registry" ],
    [ "TagInfo", "struct_catch_1_1_tag_info.html", "struct_catch_1_1_tag_info" ],
    [ "TAPReporter", "struct_catch_1_1_t_a_p_reporter.html", "struct_catch_1_1_t_a_p_reporter" ],
    [ "TeamCityReporter", "struct_catch_1_1_team_city_reporter.html", "struct_catch_1_1_team_city_reporter" ],
    [ "TestCase", "class_catch_1_1_test_case.html", "class_catch_1_1_test_case" ],
    [ "TestCaseInfo", "struct_catch_1_1_test_case_info.html", "struct_catch_1_1_test_case_info" ],
    [ "TestCaseStats", "struct_catch_1_1_test_case_stats.html", "struct_catch_1_1_test_case_stats" ],
    [ "TestEventListenerBase", "struct_catch_1_1_test_event_listener_base.html", "struct_catch_1_1_test_event_listener_base" ],
    [ "TestFailureException", "struct_catch_1_1_test_failure_exception.html", null ],
    [ "TestGroupStats", "struct_catch_1_1_test_group_stats.html", "struct_catch_1_1_test_group_stats" ],
    [ "TestInvokerAsFunction", "class_catch_1_1_test_invoker_as_function.html", "class_catch_1_1_test_invoker_as_function" ],
    [ "TestInvokerAsMethod", "class_catch_1_1_test_invoker_as_method.html", "class_catch_1_1_test_invoker_as_method" ],
    [ "TestRegistry", "class_catch_1_1_test_registry.html", "class_catch_1_1_test_registry" ],
    [ "TestRunInfo", "struct_catch_1_1_test_run_info.html", "struct_catch_1_1_test_run_info" ],
    [ "TestRunStats", "struct_catch_1_1_test_run_stats.html", "struct_catch_1_1_test_run_stats" ],
    [ "TestSpec", "class_catch_1_1_test_spec.html", "class_catch_1_1_test_spec" ],
    [ "TestSpecParser", "class_catch_1_1_test_spec_parser.html", "class_catch_1_1_test_spec_parser" ],
    [ "Timer", "class_catch_1_1_timer.html", "class_catch_1_1_timer" ],
    [ "Totals", "struct_catch_1_1_totals.html", "struct_catch_1_1_totals" ],
    [ "true_given", "struct_catch_1_1true__given.html", null ],
    [ "UnaryExpr", "class_catch_1_1_unary_expr.html", "class_catch_1_1_unary_expr" ],
    [ "UseColour", "struct_catch_1_1_use_colour.html", "struct_catch_1_1_use_colour" ],
    [ "Version", "struct_catch_1_1_version.html", "struct_catch_1_1_version" ],
    [ "WaitForKeypress", "struct_catch_1_1_wait_for_keypress.html", "struct_catch_1_1_wait_for_keypress" ],
    [ "WarnAbout", "struct_catch_1_1_warn_about.html", "struct_catch_1_1_warn_about" ],
    [ "WildcardPattern", "class_catch_1_1_wildcard_pattern.html", "class_catch_1_1_wildcard_pattern" ],
    [ "XmlEncode", "class_catch_1_1_xml_encode.html", "class_catch_1_1_xml_encode" ],
    [ "XmlReporter", "class_catch_1_1_xml_reporter.html", "class_catch_1_1_xml_reporter" ],
    [ "XmlWriter", "class_catch_1_1_xml_writer.html", "class_catch_1_1_xml_writer" ]
];